ORG	8000H
	MOV	P1,#0FFH
LOOP:	MOV	A,#3FH
	JNB	P1.0,SHOWDATA
	MOV	A,#06H
	JNB	P1.1,SHOWDATA
	MOV	A,#5BH
	JNB	P1.2,SHOWDATA
	MOV	A,#4FH
	JNB	P1.3,SHOWDATA
	MOV	A,#66H
	JNB	P1.4,SHOWDATA
	MOV	A,#6DH
	JNB	P1.5,SHOWDATA
	MOV	A,#7DH
	JNB	P1.6,SHOWDATA
	MOV	A,#07H
	JNB	P1.7,SHOWDATA
	MOV	A,#7FH
	JMP	SHOWDATA
	JMP	LOOP

SHOWDATA:
	MOV	DPTR,#0E060H
	MOVX	@DPTR,A
	JMP	LOOP
	END